import {describe,it} from 'node:test';import assert from 'node:assert/strict';
import {defaultState,forgeOperative,resolvePlayerAction} from './engine';
import {availableScenarios,availableApproaches,resolveScenarioApproach,scenarioById} from './scenario';
import {CANON_EQUIPMENT,canonItem} from './canon-equipment';
import {recordCanonBossDefeat,tyroneRebuilt,fieldLoad,itemLoad,restoreSupplies} from './canon-combat';
import {restoreNarrative} from './narrative-state';import {reloadWeapon} from './weapon-ops';
import {SERVER_TREASURE_BY_REGION,authorityTemplateByKey} from './authority-items';
function game(){const s=defaultState();s.started=true;for(const loc of Object.values(s.locations))loc.intel=4;const op=forgeOperative({name:'Courier',cls:'Warrior',race:'Human',lineage:'',origin:'Ironclad',day:1});op.inventory=[];op.hp=100;op.maxHp=100;s.operatives=[op];s.vault=[];return s;}
function choose(s:ReturnType<typeof game>,scene:string,choice:string){assert.ok(resolveScenarioApproach(s,`canon_${scene}`,choice),`${scene}:${choice} must be available`);}
function campaign(s:ReturnType<typeof game>,archive='bound'){for(const [scene,choice] of [['bay','consent'],['courier','deliver'],['hound','compact'],['lyra','witness'],['furnace','union'],['survey','protect'],['rebuild','consent'],['archive',archive],['vera','charter'],['orion','agency'],['boundary','legal'],['soren','consent']])choose(s,scene,choice);}
function fight(){const s=game(),op=s.operatives[0],gun=canonItem('Manifest','test-gun','authorized',1);gun.equipped=true;op.inventory=[gun];s.combat={locationId:'ironclad' as const,missionKind:'raid' as const,partyIds:[op.id],enemies:[{id:'target',name:'Practice rig',hp:1000,maxHp:1000,atk:0,def:0,dc:1,tags:[],flavor:''}],turn:1,actorIndex:0,log:[],rewardMult:1};return{s,op,gun};}
describe('canonical campaign',()=>{
 for(const [choice,archive,ending] of [['porchlight','bound','porchlight_accord'],['civic','bound','civic_restoration'],['coalition','bound','free_hollow_coalition'],['quiet','isolate','quiet_earth'],['directorate','bound','directorate_holds'],['continuity','vesper','civitas_return']])it(`earns ${ending} through a complete route`,()=>{const s=game();campaign(s,archive);choose(s,'finale',choice);assert.equal(s.narrative?.endingId,ending);});
 it('gates convergence, preserves serialized choices, and never repeats grants',()=>{const s=game();assert.ok(!availableScenarios(s).some(x=>x.id==='canon_finale'));campaign(s);assert.equal(tyroneRebuilt(s),true);choose(s,'finale','porchlight');const count=s.vault.length;assert.equal(resolveScenarioApproach(s,'canon_finale','porchlight'),null);assert.equal(s.vault.length,count);assert.equal(new Set(s.vault.map(i=>i.name)).size,count);assert.equal(restoreNarrative(JSON.parse(JSON.stringify(s.narrative))).beats.canon_rebuild.choiceId,'consent');});
 it('a dead witness cannot be negotiated back to life; damaged hardware is issued once',()=>{const s=game();choose(s,'bay','consent');recordCanonBossDefeat(s,'gravenor');assert.equal(resolveScenarioApproach(s,'canon_hound','compact'),null);assert.equal(s.vault.find(i=>i.name==="Hound's Tooth")?.condition,'Damaged');const count=s.vault.length;recordCanonBossDefeat(s,'gravenor');assert.equal(s.vault.length,count);});
 it('coercion closes consent-based endings',()=>{const s=game();campaign(s);s.narrative!.beats.canon_soren.choiceId='coerce';s.tyrone.relationship.trust=10;const ids=availableApproaches(s,scenarioById('canon_finale')!).map(x=>x.id);assert.ok(!ids.includes('porchlight'));assert.ok(!ids.includes('civic'));assert.ok(ids.includes('directorate'));});
 it('story gear stays out of random treasure while old owned equipment still resolves',()=>{const names=new Set(CANON_EQUIPMENT.map(i=>i.name));for(const pool of Object.values(SERVER_TREASURE_BY_REGION))assert.ok(pool.every(i=>!names.has(i.name)));assert.ok(authorityTemplateByKey('weapon:watchworks m16 service'));assert.ok(authorityTemplateByKey('weapon:obsidian coilgun'));});
});
describe('live tactical combat',()=>{
 it('spends rounds and keeps that expenditure across ownership refresh',()=>{const{s,gun}=fight(),before=gun.mag!;resolvePlayerAction(s,'strike');assert.equal(gun.mag,before-1);assert.equal(restoreSupplies(s,{...gun,mag:30}).mag,before-1);gun.condition='Broken';const turn=s.combat!.turn;resolvePlayerAction(s,'strike');assert.equal(gun.mag,before-1);assert.equal(s.combat!.turn,turn);});
 it('aim spends a turn and is consumed by the next strike',()=>{const{s,op}=fight();resolvePlayerAction(s,'aim');assert.equal(s.combat!.aimId,op.id);assert.equal(s.combat!.turn,2);resolvePlayerAction(s,'strike');assert.equal(s.combat!.aimId,undefined);});
 it('support requires the consensual rebuild and works once per encounter',()=>{const{s}=fight();resolvePlayerAction(s,'support');assert.equal(s.combat!.turn,1);s.narrative!.beats.canon_rebuild={id:'canon_rebuild',status:'done',day:1,choiceId:'consent'};resolvePlayerAction(s,'support');assert.equal(s.combat!.supportUsed,true);const turn=s.combat!.turn;resolvePlayerAction(s,'support');assert.equal(s.combat!.turn,turn);});
 it('healing cannot drink ammunition and laser cells cannot feed plasma',()=>{const{s,op}=fight(),halo=canonItem('Halo Lance','halo','authorized',1);halo.mag=0;op.inventory=[halo,{...halo,id:'ammo',name:'Laser capacitor',kind:'consumable',ammoType:'laser',ammoCount:12,equipped:false,effect:'Laser ammunition'}];assert.equal(reloadWeapon(op,halo),null);resolvePlayerAction(s,'item');assert.equal(op.inventory.length,2);assert.equal(s.combat!.turn,1);});
 it('uses a 12-load budget and negligible credentials',()=>{const{op}=fight();assert.equal(itemLoad(canonItem('Deadman Key','key','found',1)),0);op.inventory=Array.from({length:5},(_,i)=>canonItem("Hound's Tooth",String(i),'found',1));assert.deepEqual(fieldLoad(op),{load:20,capacity:12,penalty:4});});
});
