/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTyroneClaimRouteImport } from './routes/api/tyrone/claim'
import { Route as ApiTyroneSyncRouteImport } from './routes/api/tyrone/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTyroneClaimRoute = ApiTyroneClaimRouteImport.update({
  id: '/api/tyrone/claim',
  path: '/api/tyrone/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTyroneSyncRoute = ApiTyroneSyncRouteImport.update({
  id: '/api/tyrone/sync',
  path: '/api/tyrone/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/tyrone/claim' | '/api/tyrone/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/tyrone/claim' | '/api/tyrone/sync'
  id: '__root__' | '/' | '/api/tyrone/claim' | '/api/tyrone/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTyroneClaimRoute: typeof ApiTyroneClaimRoute
  ApiTyroneSyncRoute: typeof ApiTyroneSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tyrone/claim': {
      id: '/api/tyrone/claim'
      path: '/api/tyrone/claim'
      fullPath: '/api/tyrone/claim'
      preLoaderRoute: typeof ApiTyroneClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tyrone/sync': {
      id: '/api/tyrone/sync'
      path: '/api/tyrone/sync'
      fullPath: '/api/tyrone/sync'
      preLoaderRoute: typeof ApiTyroneSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTyroneClaimRoute: ApiTyroneClaimRoute,
  ApiTyroneSyncRoute: ApiTyroneSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}