/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiHollowAccessRouteImport } from './routes/api/hollow/access'
import { Route as ApiHollowAcquisitionRouteImport } from './routes/api/hollow/acquisition'
import { Route as ApiHollowEconomyRouteImport } from './routes/api/hollow/economy'
import { Route as ApiHollowInventoryRouteImport } from './routes/api/hollow/inventory'
import { Route as ApiHollowPorchRouteImport } from './routes/api/hollow/porch'
import { Route as ApiHollowProgressionRouteImport } from './routes/api/hollow/progression'
import { Route as ApiTyroneClaimRouteImport } from './routes/api/tyrone/claim'
import { Route as ApiTyroneSpeakRouteImport } from './routes/api/tyrone/speak'
import { Route as ApiTyroneSyncRouteImport } from './routes/api/tyrone/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowAccessRoute = ApiHollowAccessRouteImport.update({
  id: '/api/hollow/access',
  path: '/api/hollow/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowAcquisitionRoute = ApiHollowAcquisitionRouteImport.update({
  id: '/api/hollow/acquisition',
  path: '/api/hollow/acquisition',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowEconomyRoute = ApiHollowEconomyRouteImport.update({
  id: '/api/hollow/economy',
  path: '/api/hollow/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowInventoryRoute = ApiHollowInventoryRouteImport.update({
  id: '/api/hollow/inventory',
  path: '/api/hollow/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowPorchRoute = ApiHollowPorchRouteImport.update({
  id: '/api/hollow/porch',
  path: '/api/hollow/porch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHollowProgressionRoute = ApiHollowProgressionRouteImport.update({
  id: '/api/hollow/progression',
  path: '/api/hollow/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTyroneClaimRoute = ApiTyroneClaimRouteImport.update({
  id: '/api/tyrone/claim',
  path: '/api/tyrone/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTyroneSpeakRoute = ApiTyroneSpeakRouteImport.update({
  id: '/api/tyrone/speak',
  path: '/api/tyrone/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTyroneSyncRoute = ApiTyroneSyncRouteImport.update({
  id: '/api/tyrone/sync',
  path: '/api/tyrone/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/hollow/access': typeof ApiHollowAccessRoute
  '/api/hollow/acquisition': typeof ApiHollowAcquisitionRoute
  '/api/hollow/economy': typeof ApiHollowEconomyRoute
  '/api/hollow/inventory': typeof ApiHollowInventoryRoute
  '/api/hollow/porch': typeof ApiHollowPorchRoute
  '/api/hollow/progression': typeof ApiHollowProgressionRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/speak': typeof ApiTyroneSpeakRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/hollow/access': typeof ApiHollowAccessRoute
  '/api/hollow/acquisition': typeof ApiHollowAcquisitionRoute
  '/api/hollow/economy': typeof ApiHollowEconomyRoute
  '/api/hollow/inventory': typeof ApiHollowInventoryRoute
  '/api/hollow/porch': typeof ApiHollowPorchRoute
  '/api/hollow/progression': typeof ApiHollowProgressionRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/speak': typeof ApiTyroneSpeakRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/hollow/access': typeof ApiHollowAccessRoute
  '/api/hollow/acquisition': typeof ApiHollowAcquisitionRoute
  '/api/hollow/economy': typeof ApiHollowEconomyRoute
  '/api/hollow/inventory': typeof ApiHollowInventoryRoute
  '/api/hollow/porch': typeof ApiHollowPorchRoute
  '/api/hollow/progression': typeof ApiHollowProgressionRoute
  '/api/tyrone/claim': typeof ApiTyroneClaimRoute
  '/api/tyrone/speak': typeof ApiTyroneSpeakRoute
  '/api/tyrone/sync': typeof ApiTyroneSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/rtc'
    | '/api/hollow/access'
    | '/api/hollow/acquisition'
    | '/api/hollow/economy'
    | '/api/hollow/inventory'
    | '/api/hollow/porch'
    | '/api/hollow/progression'
    | '/api/tyrone/claim'
    | '/api/tyrone/speak'
    | '/api/tyrone/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/rtc'
    | '/api/hollow/access'
    | '/api/hollow/acquisition'
    | '/api/hollow/economy'
    | '/api/hollow/inventory'
    | '/api/hollow/porch'
    | '/api/hollow/progression'
    | '/api/tyrone/claim'
    | '/api/tyrone/speak'
    | '/api/tyrone/sync'
  id:
    | '__root__'
    | '/'
    | '/api/rtc'
    | '/api/hollow/access'
    | '/api/hollow/acquisition'
    | '/api/hollow/economy'
    | '/api/hollow/inventory'
    | '/api/hollow/porch'
    | '/api/hollow/progression'
    | '/api/tyrone/claim'
    | '/api/tyrone/speak'
    | '/api/tyrone/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiHollowAccessRoute: typeof ApiHollowAccessRoute
  ApiHollowAcquisitionRoute: typeof ApiHollowAcquisitionRoute
  ApiHollowEconomyRoute: typeof ApiHollowEconomyRoute
  ApiHollowInventoryRoute: typeof ApiHollowInventoryRoute
  ApiHollowPorchRoute: typeof ApiHollowPorchRoute
  ApiHollowProgressionRoute: typeof ApiHollowProgressionRoute
  ApiTyroneClaimRoute: typeof ApiTyroneClaimRoute
  ApiTyroneSpeakRoute: typeof ApiTyroneSpeakRoute
  ApiTyroneSyncRoute: typeof ApiTyroneSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/access': {
      id: '/api/hollow/access'
      path: '/api/hollow/access'
      fullPath: '/api/hollow/access'
      preLoaderRoute: typeof ApiHollowAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/acquisition': {
      id: '/api/hollow/acquisition'
      path: '/api/hollow/acquisition'
      fullPath: '/api/hollow/acquisition'
      preLoaderRoute: typeof ApiHollowAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/economy': {
      id: '/api/hollow/economy'
      path: '/api/hollow/economy'
      fullPath: '/api/hollow/economy'
      preLoaderRoute: typeof ApiHollowEconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/inventory': {
      id: '/api/hollow/inventory'
      path: '/api/hollow/inventory'
      fullPath: '/api/hollow/inventory'
      preLoaderRoute: typeof ApiHollowInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/porch': {
      id: '/api/hollow/porch'
      path: '/api/hollow/porch'
      fullPath: '/api/hollow/porch'
      preLoaderRoute: typeof ApiHollowPorchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hollow/progression': {
      id: '/api/hollow/progression'
      path: '/api/hollow/progression'
      fullPath: '/api/hollow/progression'
      preLoaderRoute: typeof ApiHollowProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tyrone/claim': {
      id: '/api/tyrone/claim'
      path: '/api/tyrone/claim'
      fullPath: '/api/tyrone/claim'
      preLoaderRoute: typeof ApiTyroneClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tyrone/speak': {
      id: '/api/tyrone/speak'
      path: '/api/tyrone/speak'
      fullPath: '/api/tyrone/speak'
      preLoaderRoute: typeof ApiTyroneSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tyrone/sync': {
      id: '/api/tyrone/sync'
      path: '/api/tyrone/sync'
      fullPath: '/api/tyrone/sync'
      preLoaderRoute: typeof ApiTyroneSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiHollowAccessRoute: ApiHollowAccessRoute,
  ApiHollowAcquisitionRoute: ApiHollowAcquisitionRoute,
  ApiHollowEconomyRoute: ApiHollowEconomyRoute,
  ApiHollowInventoryRoute: ApiHollowInventoryRoute,
  ApiHollowPorchRoute: ApiHollowPorchRoute,
  ApiHollowProgressionRoute: ApiHollowProgressionRoute,
  ApiTyroneClaimRoute: ApiTyroneClaimRoute,
  ApiTyroneSpeakRoute: ApiTyroneSpeakRoute,
  ApiTyroneSyncRoute: ApiTyroneSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
